name: v2o5_binder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - ipykernel=5.3.2
  - matplotlib=3.2.2
  - uncertainties=3.1.4
  - numpy=1.18.5
  - scipy=1.5.0
  - pandas=1.0.5
  - xlrd=1.2.0
